services:
    controller-A1:
        image: confluentinc/cp-server:7.8.1
        hostname: controller-A1
        container_name: controller-A1
        volumes:
            - data-controller-A1:/var/lib/kafka/data
        healthcheck:
            test: kafka-metadata-quorum --bootstrap-controller controller-A1:19093 describe --status >/dev/null 2>&1
            interval: 15s
            retries: 3
        environment:
            KAFKA_NODE_ID: 9991
            CLUSTER_ID: Nk018hRAQFytWskYqtQduw
            KAFKA_PROCESS_ROLES: controller
            KAFKA_LISTENERS: CONTROLLER://controller-A1:19093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CONTROLLER_QUORUM_VOTERS: 9991@controller-A1:19093
            KAFKA_JMX_PORT: 9999
            KAFKA_JMX_HOSTNAME: controller-A1
            KAFKA_BROKER_RACK: rack-0
            KAFKA_DEFAULT_REPLICATION_FACTOR: 3
            KAFKA_OFFSET_REPLICATION_FACTOR: 3
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
            KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 3
            KAFKA_CONFLUENT_METADATA_TOPIC_REPLICATION_FACTOR: 3
            KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 3
            # KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
            # KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
            KAFKA_CONFLUENT_BALANCER_ENABLE: false
            # KAFKA_GROUP_COORDINATOR_REBALANCE_PROTOCOLS: classic,consumer
            # KAFKA_TRANSACTION_PARTITION_VERIFICATION_ENABLE: false

        cap_add:
            - NET_ADMIN
        ports:
            - "19093:19093"

    kafka-A1:
        image: confluentinc/cp-server:7.8.1
        hostname: kafka-A1
        container_name: kafka-A1
        volumes:
            - data-kafka-A1:/var/lib/kafka/data
        healthcheck:
            test: nc -z kafka-A1 9092
            interval: 15s
            retries: 3
        depends_on:
            controller-A1:
                condition: service_healthy
        environment:
            KAFKA_LISTENERS: DOCKER://kafka-A1:9092, EXTERNAL://kafka-A1:19092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka-A1:9092, EXTERNAL://localhost:19092
            KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_JMX_PORT: 10001
            KAFKA_JMX_HOSTNAME: localhost
            KAFKA_BROKER_RACK: rack-0
            KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
            KAFKA_NODE_ID: 1
            CLUSTER_ID: Nk018hRAQFytWskYqtQduw
            KAFKA_CONTROLLER_QUORUM_VOTERS: 9991@controller-A1:19093
            KAFKA_PROCESS_ROLES: broker
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-A1:9092,kafka-A2:9092,kafka-A3:9092
            KAFKA_CONFLUENT_BALANCER_ENABLE: false
            # KAFKA_GROUP_COORDINATOR_REBALANCE_PROTOCOLS: classic,consumer
            # KAFKA_TRANSACTION_PARTITION_VERIFICATION_ENABLE: false
        cap_add:
            - NET_ADMIN
        ports:
            - "19092:19092"
            - "10001:10001"

    kafka-A2:
        image: confluentinc/cp-server:7.8.1
        hostname: kafka-A2
        container_name: kafka-A2
        volumes:
            - data-kafka-A2:/var/lib/kafka/data
        healthcheck:
            test: nc -z kafka-A2 9092
            interval: 15s
            retries: 3
        depends_on:
            controller-A1:
                condition: service_healthy
        environment:
            KAFKA_LISTENERS: DOCKER://kafka-A2:9092, EXTERNAL://kafka-A2:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka-A2:9092, EXTERNAL://localhost:29092
            KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_JMX_PORT: 10002
            KAFKA_JMX_HOSTNAME: localhost
            KAFKA_BROKER_RACK: rack-0
            KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
            KAFKA_NODE_ID: 2
            CLUSTER_ID: Nk018hRAQFytWskYqtQduw
            KAFKA_CONTROLLER_QUORUM_VOTERS: 9991@controller-A1:19093
            KAFKA_PROCESS_ROLES: broker
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-A1:9092,kafka-A2:9092,kafka-A3:9092
            KAFKA_CONFLUENT_BALANCER_ENABLE: false
            # KAFKA_GROUP_COORDINATOR_REBALANCE_PROTOCOLS: classic,consumer
            # KAFKA_TRANSACTION_PARTITION_VERIFICATION_ENABLE: false
        cap_add:
            - NET_ADMIN
        ports:
            - "29092:29092"
            - "10002:10002"

    kafka-A3:
        image: confluentinc/cp-server:7.8.1
        hostname: kafka-A3
        container_name: kafka-A3
        volumes:
            - data-kafka-A3:/var/lib/kafka/data
        healthcheck:
            test: nc -z kafka-A3 9092
            interval: 15s
            retries: 3
        depends_on:
            controller-A1:
                condition: service_healthy
        environment:
            KAFKA_LISTENERS: DOCKER://kafka-A3:9092, EXTERNAL://kafka-A3:39092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka-A3:9092, EXTERNAL://localhost:39092
            KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_JMX_PORT: 10003
            KAFKA_JMX_HOSTNAME: localhost
            KAFKA_BROKER_RACK: rack-0
            KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
            KAFKA_NODE_ID: 3
            CLUSTER_ID: Nk018hRAQFytWskYqtQduw
            KAFKA_CONTROLLER_QUORUM_VOTERS: 9991@controller-A1:19093
            KAFKA_PROCESS_ROLES: broker
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-A1:9092,kafka-A2:9092,kafka-A3:9092
            KAFKA_CONFLUENT_BALANCER_ENABLE: false
            # KAFKA_GROUP_COORDINATOR_REBALANCE_PROTOCOLS: classic,consumer
            # KAFKA_TRANSACTION_PARTITION_VERIFICATION_ENABLE: false
        cap_add:
            - NET_ADMIN
        ports:
            - "39092:39092"
            - "10003:10003"

    schema-registry-A1:
        image: confluentinc/cp-schema-registry:7.8.1
        hostname: schema-registry-A1
        container_name: schema-registry-A1
        healthcheck:
            test: curl -fail --silent http://schema-registry-A1:8081/subjects --output /dev/null || exit 1
            interval: 30s
            retries: 10
            start_period: 20s
        depends_on:
            kafka-A1:
                condition: service_healthy
            kafka-A2:
                condition: service_healthy
            kafka-A3:
                condition: service_healthy
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry-A1
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-A1:9092,kafka-A2:9092,kafka-A3:9092
            SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
            SCHEMA_REGISTRY_RESOURCE_EXTENSION_CLASS: io.confluent.schema.exporter.SchemaExporterResourceExtension
            SCHEMA_REGISTRY_KAFKASTORE_UPDATE_HANDLERS: io.confluent.schema.exporter.storage.SchemaExporterUpdateHandler
            SCHEMA_REGISTRY_PASSWORD_ENCODER_SECRET: changeme
        ports:
            - "8081:8081"

    controller-B1:
        image: confluentinc/cp-server:7.8.1
        hostname: controller-B1
        container_name: controller-B1
        volumes:
            - data-controller-B1:/var/lib/kafka/data
        healthcheck:
            test: kafka-metadata-quorum --bootstrap-controller controller-B1:19193 describe --status >/dev/null 2>&1
            interval: 15s
            retries: 3
        environment:
            KAFKA_NODE_ID: 9992
            CLUSTER_ID: CGO4QV6YQtmwRivSayL_Hw
            KAFKA_PROCESS_ROLES: controller
            KAFKA_LISTENERS: CONTROLLER://controller-B1:19193
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CONTROLLER_QUORUM_VOTERS: 9992@controller-B1:19193
            KAFKA_JMX_PORT: 9999
            KAFKA_JMX_HOSTNAME: controller-B1
            KAFKA_BROKER_RACK: rack-0
            KAFKA_DEFAULT_REPLICATION_FACTOR: 3
            KAFKA_OFFSET_REPLICATION_FACTOR: 3
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
            KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 3
            KAFKA_CONFLUENT_METADATA_TOPIC_REPLICATION_FACTOR: 3
            KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 3
            # KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
            # KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
            KAFKA_CONFLUENT_BALANCER_ENABLE: false
            # KAFKA_GROUP_COORDINATOR_REBALANCE_PROTOCOLS: classic,consumer
            # KAFKA_TRANSACTION_PARTITION_VERIFICATION_ENABLE: false

        cap_add:
            - NET_ADMIN
        ports:
            - "19193:19193"

    kafka-B1:
        image: confluentinc/cp-server:7.8.1
        hostname: kafka-B1
        container_name: kafka-B1
        volumes:
            - data-kafka-B1:/var/lib/kafka/data
        healthcheck:
            test: nc -z kafka-B1 9192
            interval: 15s
            retries: 3
        depends_on:
            controller-B1:
                condition: service_healthy
        environment:
            KAFKA_LISTENERS: DOCKER://kafka-B1:9192, EXTERNAL://kafka-B1:19192
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka-B1:9192, EXTERNAL://localhost:19192
            KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_JMX_PORT: 11001
            KAFKA_JMX_HOSTNAME: localhost
            KAFKA_BROKER_RACK: rack-0
            KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
            KAFKA_NODE_ID: 1
            CLUSTER_ID: CGO4QV6YQtmwRivSayL_Hw
            KAFKA_CONTROLLER_QUORUM_VOTERS: 9992@controller-B1:19193
            KAFKA_PROCESS_ROLES: broker
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-B1:9092,kafka-B2:9092,kafka-B3:9092
            KAFKA_CONFLUENT_BALANCER_ENABLE: false
            KAFKA_CONFLUENT_CLUSTER_LINK_ENABLE: true
            # KAFKA_GROUP_COORDINATOR_REBALANCE_PROTOCOLS: classic,consumer
            # KAFKA_TRANSACTION_PARTITION_VERIFICATION_ENABLE: false
        cap_add:
            - NET_ADMIN
        ports:
            - "19192:19192"
            - "11001:11001"

    kafka-B2:
        image: confluentinc/cp-server:7.8.1
        hostname: kafka-B2
        container_name: kafka-B2
        volumes:
            - data-kafka-B2:/var/lib/kafka/data
        healthcheck:
            test: nc -z kafka-B2 9192
            interval: 15s
            retries: 3
        depends_on:
            controller-B1:
                condition: service_healthy
        environment:
            KAFKA_LISTENERS: DOCKER://kafka-B2:9192, EXTERNAL://kafka-B2:29192
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka-B2:9192, EXTERNAL://localhost:29192
            KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_JMX_PORT: 11002
            KAFKA_JMX_HOSTNAME: localhost
            KAFKA_BROKER_RACK: rack-0
            KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
            KAFKA_NODE_ID: 2
            CLUSTER_ID: CGO4QV6YQtmwRivSayL_Hw
            KAFKA_CONTROLLER_QUORUM_VOTERS: 9992@controller-B1:19193
            KAFKA_PROCESS_ROLES: broker
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-B1:9092,kafka-B2:9092,kafka-B3:9092
            KAFKA_CONFLUENT_BALANCER_ENABLE: false
            KAFKA_CONFLUENT_CLUSTER_LINK_ENABLE: true
            # KAFKA_GROUP_COORDINATOR_REBALANCE_PROTOCOLS: classic,consumer
            # KAFKA_TRANSACTION_PARTITION_VERIFICATION_ENABLE: false
        cap_add:
            - NET_ADMIN
        ports:
            - "29192:29192"
            - "11002:11002"

    kafka-B3:
        image: confluentinc/cp-server:7.8.1
        hostname: kafka-B3
        container_name: kafka-B3
        volumes:
            - data-kafka-B3:/var/lib/kafka/data
        healthcheck:
            test: nc -z kafka-B3 9192
            interval: 15s
            retries: 3
        depends_on:
            controller-B1:
                condition: service_healthy
        environment:
            KAFKA_LISTENERS: DOCKER://kafka-B3:9192, EXTERNAL://kafka-B3:39192
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka-B3:9192, EXTERNAL://localhost:39192
            KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_JMX_PORT: 11003
            KAFKA_JMX_HOSTNAME: localhost
            KAFKA_BROKER_RACK: rack-0
            KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
            KAFKA_NODE_ID: 3
            CLUSTER_ID: CGO4QV6YQtmwRivSayL_Hw
            KAFKA_CONTROLLER_QUORUM_VOTERS: 9992@controller-B1:19193
            KAFKA_PROCESS_ROLES: broker
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-B1:9192,kafka-B2:9192,kafka-B3:9192
            KAFKA_CONFLUENT_BALANCER_ENABLE: false
            KAFKA_CONFLUENT_CLUSTER_LINK_ENABLE: true
            # KAFKA_GROUP_COORDINATOR_REBALANCE_PROTOCOLS: classic,consumer
            # KAFKA_TRANSACTION_PARTITION_VERIFICATION_ENABLE: false
        cap_add:
            - NET_ADMIN
        ports:
            - "39192:39192"
            - "11003:11003"

    schema-registry-B1:
        image: confluentinc/cp-schema-registry:7.8.1
        hostname: schema-registry-B1
        container_name: schema-registry-B1
        healthcheck:
            test: curl -fail --silent http://schema-registry-B1:8181/subjects --output /dev/null || exit 1
            interval: 30s
            retries: 10
            start_period: 20s
        depends_on:
            kafka-B1:
                condition: service_healthy
            kafka-B2:
                condition: service_healthy
            kafka-B3:
                condition: service_healthy
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry-B1
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-B1:9192,kafka-B2:9192,kafka-B3:9192
            SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8181
            SCHEMA_REGISTRY_RESOURCE_EXTENSION_CLASS: io.confluent.schema.exporter.SchemaExporterResourceExtension
            SCHEMA_REGISTRY_KAFKASTORE_UPDATE_HANDLERS: io.confluent.schema.exporter.storage.SchemaExporterUpdateHandler
            SCHEMA_REGISTRY_PASSWORD_ENCODER_SECRET: changeme
        ports:
            - "8181:8181"


    control-center:
        image: confluentinc/cp-enterprise-control-center:7.8.1
        hostname: control-center
        container_name: control-center
        depends_on:
            kafka-A1:
                condition: service_healthy
            kafka-A2:
                condition: service_healthy
            kafka-A3:
                condition: service_healthy
            schema-registry-A1:
                condition: service_healthy
            # kafka-connect:
            #     condition: service_healthy
        environment:
            CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka-A1:9092
            CONTROL_CENTER_KAFKA_B_BOOTSTRAP_SERVERS: kafka-B1:9192
            CONTROL_CENTER_SCHEMA_REGISTRY_URL: http://schema-registry-A1:8081
            CONTROL_CENTER_KAFKA_B_SCHEMA_REGISTRY_URL: http://schema-registry-B1:8181
            CONTROL_CENTER_REPLICATION_FACTOR: 3
        ports:
            - "9021:9021"
        profiles: []

    initializer:
        image: cnfltraining/training-tools:7.5
        restart: always
        hostname: tools
        container_name: tools
        volumes:
            - ${PWD}:/apps
        environment:
            CLASSPATH: "/usr/share/java/monitoring-interceptors/monitoring-interceptors-7.5.3.jar"
        working_dir: /apps
        command: /bin/bash
        tty: true
        profiles:
        - inactive



    tools:
        image: cnfltraining/training-tools:7.5
        restart: always
        hostname: tools
        container_name: tools
        volumes:
            - ${PWD}:/apps
        environment:
            CLASSPATH: "/usr/share/java/monitoring-interceptors/monitoring-interceptors-7.5.3.jar"
        working_dir: /apps
        command: /bin/bash
        tty: true
        profiles:
        - inactive


volumes:
    data-controller-A1:
    data-kafka-A1:
    data-kafka-A2:
    data-kafka-A3:
    data-controller-B1:
    data-kafka-B1:
    data-kafka-B2:
    data-kafka-B3:
