acl.sync.enable=true
auto.create.mirror.topics.enable=true
consumer.offset.sync.enable=true

# configuration for connecting to source cluster
bootstrap.servers=kakfa-A1:9092,kakfa-A2:9092,kafka-A3:9092
