[project]
name = "card-event-generator"
version = "0.1.0"
description = ""
authors = [
    {name = "Randy May",email = "randy@mathysphere.com"}
]
requires-python = ">=3.12"
dependencies = [
    "faker (>=40.19.1,<41.0.0)",
    "avro (>=1.12.1,<2.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode= false
