{
    "type": "record",
    "namespace": "io.confluent.sample",
    "name": "CreditCard",
    "fields": [
        {
            "name": "provider",
            "type": {
                "type": "enum",
                "name": "Provider",
                "symbols": ["Discover","American_Express","Mastercard", "VISA", "JCB", "Diners_Club", "Maestro"]
            }
        },
        {
            "name": "cardholder_name",
            "type": "string"
        },
        {
            "name": "card_number",
            "type": "string"
        },
        {
            "name": "expiration",
            "type": {
                "type": "record",
                "name": "YearMonth",
                "fields": [
                    {
                        "name": "year",
                        "type": "int"
                    },
                    {
                        "name": "month",
                        "type" : "int"
                    }
                ]
            }
        },
        {
            "name": "verification_code",
            "type": "string"
        }
    ]
}
