apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardfraud-event-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardfraud-event-generator
  template:
    metadata:
      labels:
        app: cardfraud-event-generator
    spec:
      containers:
        - name: event-generatpr
          image: event-generator:dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: cardfraud-env
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
