apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: cardfraud-topic
spec:
  name: transactions
  replicas: 3
  partitionCount: 3
  kafkaClusterRef: 
    name: kafka
  configs:
    cleanup.policy: delete
---
apiVersion: platform.confluent.io/v1beta1
kind: Schema
metadata:
  name: cardfraud-value-schema
spec:
  name: transactions-value
  compatibilityLevel: BACKWARD
  normalize: true
  data:
    configRef: cardfraud-transaction-schema
    format: avro
  schemaRegistryClusterRef:
    name: schemaregistry

