- name: Install OpenJDK on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install OpenJDK 17
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present
