[project]
name = "aws"
version = "0.1.0"
description = ""
authors = [
    {name = "Randy May",email = "randy@mathysphere.com"}
]
requires-python = ">=3.10"
dependencies = [
    "cloudlab (>=1.2.2,<2.0.0)",
    "ansible (>=9.0.0,<10.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false