bootstrap.servers=localhost:19092,localhost:29092,localhost:39092
value.deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
key.deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
schema.registry.url=http://localhost:8081/
group.id=OrderConsumer
auto.offset.reset=earliest
batch.consumption.delay.ms=1000

