bootstrap.servers=localhost:19092,localhost:29092,localhost:39092
value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
key.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
schema.registry.url=http://localhost:8081/
auto.register.schemas=false
producer.rate.tps=10
producer.message.count=36000