name: kraft-static-quorum

x-common-env: &common-env
  CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
  KAFKA_CONTROLLER_QUORUM_VOTERS: '100@controller-dc1:9093,101@controller-dc2:9093,102@controller-dc3:9093,103@controller-dc4:9093,104@controller-dc5:9093'
  KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
  KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
  KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  KAFKA_MIN_INSYNC_REPLICAS: 2
  KAFKA_NUM_PARTITIONS: 6
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

services:
  controller-dc1:
    image: confluentinc/cp-kafka:7.8.2
    hostname: controller-dc1
    container_name: controller-dc1
    restart: unless-stopped
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 100
      KAFKA_PROCESS_ROLES: 'controller'
      KAFKA_LISTENERS: 'CONTROLLER://0.0.0.0:9093'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    # healthcheck:
    #     test: kafka-metadata-quorum --bootstrap-controller controller-dc1:9093 describe --status >/dev/null 2>&1
    #     interval: 15s
    #     retries: 3
    volumes:
      - controller-dc1-data:/var/lib/kafka/data

  broker-dc1-a:
    image: confluentinc/cp-kafka:7.8.2
    hostname: broker-dc1-a
    container_name: broker-dc1-a
    restart: unless-stopped
    depends_on: [controller-dc1, controller-dc2, controller-dc3, controller-dc4, controller-dc5]
    ports:
      - '19092:9094'
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker'
      KAFKA_BROKER_RACK: 'dc1'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://broker-dc1-a:9092,EXTERNAL://localhost:19092'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - broker-dc1-a-data:/var/lib/kafka/data
    networks:
      backbone: {}
      dc1: {}

  broker-dc1-b:
    image: confluentinc/cp-kafka:7.8.2
    hostname: broker-dc1-b
    container_name: broker-dc1-b
    restart: unless-stopped
    depends_on: [controller-dc1, controller-dc2, controller-dc3, controller-dc4, controller-dc5]
    ports:
      - '19093:9094'
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: 'broker'
      KAFKA_BROKER_RACK: 'dc1'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://broker-dc1-b:9092,EXTERNAL://localhost:19093'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - broker-dc1-b-data:/var/lib/kafka/data
    networks:
      backbone: {}
      dc1: {}

  controller-dc2:
    image: confluentinc/cp-kafka:7.8.2
    hostname: controller-dc2
    container_name: controller-dc2
    restart: unless-stopped
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 101
      KAFKA_PROCESS_ROLES: 'controller'
      KAFKA_LISTENERS: 'CONTROLLER://0.0.0.0:9093'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    # healthcheck:
    #     test: kafka-metadata-quorum --bootstrap-controller controller-dc2:9093 describe --status >/dev/null 2>&1
    #     interval: 15s
    #     retries: 3
    volumes:
      - controller-dc2-data:/var/lib/kafka/data
    networks:
      backbone: {}
      dc2: {}

  broker-dc2-a:
    image: confluentinc/cp-kafka:7.8.2
    hostname: broker-dc2-a
    container_name: broker-dc2-a
    restart: unless-stopped
    depends_on: [controller-dc1, controller-dc2, controller-dc3, controller-dc4, controller-dc5]
    ports:
      - '19094:9094'
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: 'broker'
      KAFKA_BROKER_RACK: 'dc2'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://broker-dc2-a:9092,EXTERNAL://localhost:19094'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - broker-dc2-a-data:/var/lib/kafka/data
    networks:
      backbone: {}
      dc2: {}

  broker-dc2-b:
    image: confluentinc/cp-kafka:7.8.2
    hostname: broker-dc2-b
    container_name: broker-dc2-b
    restart: unless-stopped
    depends_on: [controller-dc1, controller-dc2, controller-dc3, controller-dc4, controller-dc5]
    ports:
      - '19095:9094'
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: 'broker'
      KAFKA_BROKER_RACK: 'dc2'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://broker-dc2-b:9092,EXTERNAL://localhost:19095'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - broker-dc2-b-data:/var/lib/kafka/data
    networks:
      backbone: {}
      dc2: {}

  controller-dc3:
    image: confluentinc/cp-kafka:7.8.2
    hostname: controller-dc3
    container_name: controller-dc3
    restart: unless-stopped
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 102
      KAFKA_PROCESS_ROLES: 'controller'
      KAFKA_LISTENERS: 'CONTROLLER://0.0.0.0:9093'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    # healthcheck:
    #     test: kafka-metadata-quorum --bootstrap-controller controller-dc3:9093 describe --status >/dev/null 2>&1
    #     interval: 15s
    #     retries: 3
    volumes:
      - controller-dc3-data:/var/lib/kafka/data
    networks:
      backbone: {}
      dc3: {}

  broker-dc3-a:
    image: confluentinc/cp-kafka:7.8.2
    hostname: broker-dc3-a
    container_name: broker-dc3-a
    restart: unless-stopped
    depends_on: [controller-dc1, controller-dc2, controller-dc3, controller-dc4, controller-dc5]
    ports:
      - '19096:9094'
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 5
      KAFKA_PROCESS_ROLES: 'broker'
      KAFKA_BROKER_RACK: 'dc3'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://broker-dc3-a:9092,EXTERNAL://localhost:19096'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - broker-dc3-a-data:/var/lib/kafka/data
    networks:
      backbone: {}
      dc3: {}

  broker-dc3-b:
    image: confluentinc/cp-kafka:7.8.2
    hostname: broker-dc3-b
    container_name: broker-dc3-b
    restart: unless-stopped
    depends_on: [controller-dc1, controller-dc2, controller-dc3, controller-dc4, controller-dc5]
    ports:
      - '19097:9094'
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 6
      KAFKA_PROCESS_ROLES: 'broker'
      KAFKA_BROKER_RACK: 'dc3'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://broker-dc3-b:9092,EXTERNAL://localhost:19097'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - broker-dc3-b-data:/var/lib/kafka/data
    networks:
      backbone: {}
      dc3: {}

  controller-dc4:
    image: confluentinc/cp-kafka:7.8.2
    hostname: controller-dc4
    container_name: controller-dc4
    restart: unless-stopped
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 103
      KAFKA_PROCESS_ROLES: 'controller'
      KAFKA_LISTENERS: 'CONTROLLER://0.0.0.0:9093'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    # healthcheck:
    #     test: kafka-metadata-quorum --bootstrap-controller controller-dc4:9093 describe --status >/dev/null 2>&1
    #     interval: 15s
    #     retries: 3
    volumes:
      - controller-dc4-data:/var/lib/kafka/data
    networks:
      backbone: {}
      dc4: {}

  controller-dc5:
    image: confluentinc/cp-kafka:7.8.2
    hostname: controller-dc5
    container_name: controller-dc5
    restart: unless-stopped
    environment:
      <<: *common-env
      KAFKA_NODE_ID: 104
      KAFKA_PROCESS_ROLES: 'controller'
      KAFKA_LISTENERS: 'CONTROLLER://0.0.0.0:9093'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    # healthcheck:
    #     test: kafka-metadata-quorum --bootstrap-controller controller-dc5:9093 describe --status >/dev/null 2>&1
    #     interval: 15s
    #     retries: 3
    volumes:
      - controller-dc5-data:/var/lib/kafka/data
    networks:
      backbone: {}
      dc5: {}

networks:
  backbone:
    driver: bridge
  dc1:
    driver: bridge
  dc2:
    driver: bridge
  dc3:
    driver: bridge
  dc4:
    driver: bridge
  dc5:
    driver: bridge

volumes:
  controller-dc1-data:
  controller-dc2-data:
  controller-dc3-data:
  controller-dc4-data:
  controller-dc5-data:
  broker-dc1-a-data:
  broker-dc1-b-data:
  broker-dc2-a-data:
  broker-dc2-b-data:
  broker-dc3-a-data:
  broker-dc3-b-data:
